name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck ghostscript
    
    - name: Run ShellCheck
      run: |
        shellcheck compresskit-pdf
        shellcheck install.sh
    
    - name: Test script permissions
      run: |
        chmod +x compresskit-pdf
        chmod +x install.sh
        ./compresskit-pdf --version
    
    - name: Test installation
      run: |
        sudo ./install.sh
        compresskit-pdf --help
